# Numpy Tutorial for beginners.

Numpy which is the abbrevation of numerical python is one of the basic tools used to perform mathematical operations.In the field of data analysis the numpy cannot be understated.Let us try to get some understanding of basic commands used in Numpy.

First of all we need to import numpy with an alias np.

It doesn't matter even if you import numpy without an alias but it would ease us the burden of typing numpy everytime.

In [3]:
import numpy as np

An array can be created using np.array command and we can also specify the datatype we required in the array.For example in the below example we are creating an array of size 3 of type float.

In [4]:
np.array([1,2,3],float)

array([ 1.,  2.,  3.])

We can not only create an array with a single row but also arrays' of multiple of rows as shown below.

In [5]:
a = np.array([[1,2,3,],[8,0,1],[3,4,7]],dtype=float)

Shape of an array can be known calling the shape on array.

In [6]:
a.shape

(3, 3)

np.where can be used to perform boolean operations on the array we have.

Lets look at the example below.

In [12]:
a = np.array([100,3,100],float)
np.where(a==100,1/a,a)

array([ 0.01,  3.  ,  0.01])

Our function is doing something like this np.where(checking the condition on given element,print this if true,print this if false)

Adding an axis(i.e. an additional depth column) to an array can be done using np.newaxis command.

In [27]:
a = np.array([[1,2,3,],[8,0,1],[3,4,7]],dtype=float)
a[np.newaxis,:]

array([[[ 1.,  2.,  3.],
        [ 8.,  0.,  1.],
        [ 3.,  4.,  7.]]])

This can be better understood by seeing the shapes of two arrays

In [28]:
a.shape,a[np.newaxis,:].shape

((3, 3), (1, 3, 3))

Here by giving np.newaxis before rows and columns we are adding depth axis additionally to our array.
Visualise it in a 3Dimensional array for a better intuition.

In [21]:
a = np.array([[1,2,3],[8,0,1],[3,4,7]],dtype=float)
a[:,:,np.newaxis]

array([[[ 1.],
        [ 2.],
        [ 3.]],

       [[ 8.],
        [ 0.],
        [ 1.]],

       [[ 3.],
        [ 4.],
        [ 7.]]])

In [22]:
a[:,:,np.newaxis].shape

(3, 3, 1)

Here we are making the newaxis for column.That means depth becomes 3.

Creating a diagonal matrix using the elements given can be done using np.diag command

In [30]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

we can specify where our given elements should form as a diagonal

In [48]:
np.diag([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

Creating a random array of selected elements and selected size

To randomly output a number

In [34]:
np.random.randint(1,10)

1

To randomly select an array of specified size 

In [35]:
np.random.randint(1,100,3)

array([59, 62, 35])

Creating a random array of multiple rows and columns.

In [36]:
np.random.randint(1,100,(3,4))

array([[57, 76, 96, 27],
       [29, 34, 52, 56],
       [35, 17, 69, 29]])

Let us print array of zeros.

In [ ]:
z= np.zeros(10)

We can index it just like we did in other cases

In [38]:
z[4]=5
print (z)

[ 0.  0.  0.  0.  5.  0.  0.  0.  0.  0.]


Printing an array between range.

We can also specify step with which our range should be printed.

In [44]:
np.arange(10,50,2,float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.])

We can reverse just like the other cases.

In [45]:
a = np.arange(50,dtype=float)
b = a[::-1]
print(b)

[ 49.  48.  47.  46.  45.  44.  43.  42.  41.  40.  39.  38.  37.  36.  35.
  34.  33.  32.  31.  30.  29.  28.  27.  26.  25.  24.  23.  22.  21.  20.
  19.  18.  17.  16.  15.  14.  13.  12.  11.  10.   9.   8.   7.   6.   5.
   4.   3.   2.   1.   0.]


Reshaping can be done using reshape command.

In [46]:
a = np.arange(9).reshape(3,3)
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


We can only separate non-zero elements using non-zero command

In [48]:
a = np.array([1,2,0,0,4,0],float)
a.nonzero()

(array([0, 1, 4], dtype=int64),)

Printing an identity matrix

In [49]:
np.identity(3,float)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

or we can also print it using eye command

In [50]:
np.eye(3,k=0,dtype=float)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Random matrix of can be generated using random.random command by specifying depth,row,column.

In [51]:
np.random.random((3,3,3))

array([[[ 0.68609155,  0.23503657,  0.03325732],
        [ 0.09534678,  0.50408923,  0.28814612],
        [ 0.25004059,  0.33660801,  0.04286171]],

       [[ 0.93153643,  0.40197843,  0.11033721],
        [ 0.78547388,  0.43754195,  0.35362452],
        [ 0.37517088,  0.74125535,  0.85074315]],

       [[ 0.31064154,  0.19764225,  0.4138971 ],
        [ 0.7542043 ,  0.93257708,  0.23666394],
        [ 0.1595883 ,  0.59929832,  0.72391881]]])

To print a non array random element within the range of 0,1 we should specify size = none

In [55]:
np.random.random(size=None)

0.4232972424679775

We can print all ones or zeros or any other number we want in the following way

In [63]:
a = np.ones((2,10))
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [64]:
np.zeros((4,4),dtype = float)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Let us play around with the array values a little bit.

Try to make alternative ones and zero in all rows and columns of a 8*8 matrix.

In [66]:
z = np.zeros((8,8))
z[::2,::2] = 1
z[1::2,1::2] = 1
print (z)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


create a matrix with 1's on edges and 0's in the interior.

In [56]:
a[1:-1,1:-1]=0
print (a)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


Finding Dot product of arrays.Here elementwise multiplication.

In [58]:
np.dot((np.ones((3,2))),np.ones((2,4)))

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

we can find sum of elements using sum command.

In [68]:
a = np.arange(10)
sum(a)

45

We can find the index of max value in the array and can use to same for indexing etc.

In [ ]:
a = np.random.random(15)
c = a.argmax()
a[c]=0
print(a)

Any and All are used to check whether any or all of the values of array are returning True.

In [ ]:
a = np.array([True,False,True],dtype = bool)
any(a)
all(a)

abs can be used to return positive value of a certain value

In [ ]:
a = -1.3
abs(a)

Array indexing works same as in python

In [ ]:
a = np.array([[1,2,3],[4,7,3],[1,0,9]],float)
a[-1:,-2:]

We can find minimum value of the array along the rows and columns and this can be specified using axis command.

In [ ]:
a = np.array([[1,2,-5,-1],[3,4,9,-1],[5,6,7,8]], dtype=float)
a.min(axis=1)

Boolean indexing can be done using logical_and,logical_not,logical_or

In [70]:
a = np.array([-1, -1, 0], float)
np.logical_and(a > 0, a < 3)

array([False, False, False], dtype=bool)

In [71]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [72]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True], dtype=bool)

And the same result can be used for indexing of any other array.

In [ ]:
a = np.array([6,1,2,9,11],float)
np.logical_and(a>5,a<9)
a[np.logical_and(a>1,a<10)]

we can find the polynomial fit of the values using polyfit commands.

In [73]:
x = [1,2,3,4,4,6,5,2]
y = [3,3,4,2,3,7,8,9]
np.polyfit(x,y,3)

array([ 0.23451327, -2.19444444,  6.12610619, -0.39085546])

We can convert an array to list using tolist command.

In [ ]:
a = np.array([[1,2,3],[4,5,6]],float)
a.tolist()

we can convert an array to to string using tostring command.

In [79]:
a = np.array([1,2,3],float)
s = a.tostring()
print(s)

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


And the same can be converted back to an array using fromstring command.

In [80]:
np.fromstring(s)

array([ 1.,  2.,  3.])

We can fill all elements of an array with the number of our choice using fill command.

In [82]:
a = np.array([1,2,3],float)
a.fill(10)
print (a)

[ 10.  10.  10.]


A transpose of an array can be found using array.transpose command.

In [84]:
a=np.array(range(6),float).reshape(2,3)
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

mean of an array can be found using mean command

In [92]:
a=np.array([11,2,3,1,100.1,-12.9,0,2,31,2,1,1,-1,-2],float)

In [93]:
np.mean(a)

9.8714285714285701

The lower integer place for a decimal value is obtained by floor command

In [95]:
np.floor(a)

array([  11.,    2.,    3.,    1.,  100.,  -13.,    0.,    2.,   31.,
          2.,    1.,    1.,   -1.,   -2.])

The upper integer place for a decimal value is obtained by ceil command.

In [97]:
np.ceil(a)

array([  11.,    2.,    3.,    1.,  101.,  -12.,    0.,    2.,   31.,
          2.,    1.,    1.,   -1.,   -2.])

The above commands should be of good help for all the beginners who want to get started with numpy.